-
 name: install docker and awscli
 hosts: servers
 become: yes
 tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: latest
   - name: install aws cli
     apt:
       name: awscli
       state: latest
       when: ansible_distribution == 'Debian' or ansible_distribution == 'ubuntu'
