-
 name: this is use for upload web page in prod
 hosts: servers
 become: yes
 tasks:
   - name: Install nginx
     apt:
       name: nginx
       state: latest
   - name: Start nginx
     service:
       name: nginx
       state: started
   - name: Deploy webpage
     copy:
       src: index.html
       dest: /var/www/html
